name: Daily-Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '00 05 * * *'

jobs:
  run-daily-jobs:
    name: Run the daily cache
    runs-on: ubuntu-latest
    
    steps:
      - name: Check current directory
        run: pwd
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: python -m pip install -r requirements.txt
      - name: Run scripts
        run: cd src && python fetch_teams.py
      - name: Add changes
        run: |
          cd ..
          git add -u .
          git config user.name "Daily cache"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated daily task $GITHUB_RUN_ID" && git push
