name: Daily-Cache

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
    workflow_dispatch: # Manual trigger


jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10 # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run get_cc_league.py
      run: cd src && python get_cc_league.py

    - name: Run fetch_teams.py
      run: cd src && python fetch_teams.py

    - name: Add changes
      run: |
        cd ..
        git add -u .
        git config user.name "Daily cache"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated daily task $GITHUB_RUN_ID" && git push
